function LoadAllTextures()
	Draw.LoadTexture("hud_heart", "lua/cl/textures/hud_heart.png")
	Draw.LoadTexture("hud_book", "lua/cl/textures/hud_book.png")
	Draw.LoadTexture("hud_user", "lua/cl/textures/hud_user.png")
	Draw.LoadTextureNoFilter("hud_coins", "lua/cl/textures/hud_coins.png")

	local ItemsSet = Draw.CreateSpriteSet("lua/cl/textures/items.png", 16, 16)
	Draw.LoadSpriteTexture("item_carrot", ItemsSet, 0, 0)
	Draw.LoadSpriteTexture("item_potato", ItemsSet, 1, 0)
	Draw.LoadSpriteTexture("item_tomato", ItemsSet, 2, 0)
	Draw.LoadSpriteTexture("item_oak_wood", ItemsSet, 3, 0)
	Draw.LoadSpriteTexture("item_cod", ItemsSet, 4, 0)
	Draw.LoadSpriteTexture("item_empty_flask", ItemsSet, 5, 0)
	Draw.LoadSpriteTexture("item_empty_big_flask", ItemsSet, 6, 0)
	Draw.LoadSpriteTexture("item_empty_gigant_flask", ItemsSet, 7, 0)
	Draw.LoadSpriteTexture("item_slime_ball", ItemsSet, 8, 0)
	Draw.LoadSpriteTexture("item_string", ItemsSet, 9, 0)
	Draw.LoadSpriteTexture("item_money_bag", ItemsSet, 10, 0)
	Draw.LoadSpriteTexture("item_abyssal_sphere", ItemsSet, 11, 0)
	Draw.LoadSpriteTexture("item_copper_ore", ItemsSet, 0, 1)
	Draw.LoadSpriteTexture("item_copper_ingot", ItemsSet, 1, 1)
	Draw.LoadSpriteTexture("item_diamond", ItemsSet, 2, 1)
	Draw.LoadSpriteTexture("item_birch_wood", ItemsSet, 3, 1)
	Draw.LoadSpriteTexture("item_salmon", ItemsSet, 4, 1)
	Draw.LoadSpriteTexture("item_heal_flask", ItemsSet, 5, 1)
	Draw.LoadSpriteTexture("item_heal_big_flask", ItemsSet, 6, 1)
	Draw.LoadSpriteTexture("item_heal_gigant_flask", ItemsSet, 7, 1)
	Draw.LoadSpriteTexture("item_fire_shard", ItemsSet, 8, 1)
	Draw.LoadSpriteTexture("item_poison_shard", ItemsSet, 9, 1)
	Draw.LoadSpriteTexture("item_vortex_shard", ItemsSet, 10, 1)
	Draw.LoadSpriteTexture("item_glowing_algae", ItemsSet, 11, 1)
	Draw.LoadSpriteTexture("item_iron_ore", ItemsSet, 0, 2)
	Draw.LoadSpriteTexture("item_iron_ingot", ItemsSet, 1, 2)
	Draw.LoadSpriteTexture("item_emerald", ItemsSet, 2, 2)
	Draw.LoadSpriteTexture("item_spruce_wood", ItemsSet, 3, 2)
	Draw.LoadSpriteTexture("item_clown_fish", ItemsSet, 4, 2)
	Draw.LoadSpriteTexture("item_mana_flask", ItemsSet, 5, 2)
	Draw.LoadSpriteTexture("item_mana_big_flask", ItemsSet, 6, 2)
	Draw.LoadSpriteTexture("item_mana_gigant_flask", ItemsSet, 7, 2)
	Draw.LoadSpriteTexture("item_bone", ItemsSet, 8, 2)
	Draw.LoadSpriteTexture("item_skull", ItemsSet, 9, 2)
	Draw.LoadSpriteTexture("item_leather", ItemsSet, 10, 2)
	Draw.LoadSpriteTexture("item_green_corall", ItemsSet, 11, 2)
	Draw.LoadSpriteTexture("item_gold_ore", ItemsSet, 0, 3)
	Draw.LoadSpriteTexture("item_gold_ingot", ItemsSet, 1, 3)
	Draw.LoadSpriteTexture("item_obsidian", ItemsSet, 2, 3)
	Draw.LoadSpriteTexture("item_acacia_wood", ItemsSet, 3, 3)
	Draw.LoadSpriteTexture("item_dragon_ore", ItemsSet, 0, 4)
	Draw.LoadSpriteTexture("item_dragon_ingot", ItemsSet, 1, 4)
	Draw.LoadSpriteTexture("item_mithril_ore", ItemsSet, 0, 5)
	Draw.LoadSpriteTexture("item_mithril_ingot", ItemsSet, 1, 5)
	Draw.LoadSpriteTexture("item_orichalcum_ore", ItemsSet, 0, 6)
	Draw.LoadSpriteTexture("item_orichalcum_ingot", ItemsSet, 1, 6)
	Draw.LoadSpriteTexture("item_titanium_ore", ItemsSet, 0, 7)
	Draw.LoadSpriteTexture("item_titanium_ingot", ItemsSet, 1, 7)
	Draw.LoadSpriteTexture("item_astralium_ore", ItemsSet, 0, 8)
	Draw.LoadSpriteTexture("item_astralium_ingot", ItemsSet, 1, 8)
	Draw.DeleteSpriteSet(ItemsSet)
end


Hook.Add("OnInit", "LoadAllTextures", LoadAllTextures)
